# Generated by Django 3.2.16 on 2023-05-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('jwt_version', models.IntegerField(default=0, verbose_name='jwt版本')),
            ],
            options={
                'verbose_name': '管理员表',
                'verbose_name_plural': '管理员表',
                'db_table': 'a_admin',
            },
        ),
    ]
