# Generated by Django 3.2.16 on 2023-05-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_freeze',
            field=models.BooleanField(default=False, verbose_name='是否冻结'),
        ),
    ]
