# Generated by Django 3.2.16 on 2023-05-03 17:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import extension.custom_field_ext


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='创建时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='创建时间戳')),
                ('update_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='更新时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='更新时间戳')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='作者')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='comment.comment', verbose_name='父评论')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo', verbose_name='照片')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 'a_comment',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='创建时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='创建时间戳')),
                ('update_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='更新时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='更新时间戳')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comment')),
            ],
            options={
                'verbose_name': '回复表',
                'verbose_name_plural': '回复表',
                'db_table': 'a_reply',
                'ordering': ['-create_time'],
            },
        ),
    ]
