# Generated by Django 3.2.16 on 2023-03-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='a_comment',
        ),
    ]
