# Generated by Django 3.2.16 on 2023-04-28 21:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import extension.custom_field_ext


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_table'),
        ('comment', '0006_auto_20230428_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='创建时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='创建时间戳')),
                ('update_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='更新时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='更新时间戳')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comment')),
            ],
            options={
                'verbose_name': '回复表',
                'verbose_name_plural': '回复表',
                'db_table': 'a_reply',
            },
        ),
    ]
