# Generated by Django 3.2.16 on 2023-04-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_time'], 'verbose_name': '评论表', 'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-create_time'], 'verbose_name': '回复表', 'verbose_name_plural': '回复表'},
        ),
    ]
