# Generated by Django 3.2.16 on 2023-05-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
