# Generated by Django 3.2.16 on 2023-03-09 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import extension.custom_field_ext


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_alter_user_table'),
        ('photo', '0003_alter_photo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='创建时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='创建时间戳')),
                ('update_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='更新时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='更新时间戳')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo', verbose_name='图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏表',
                'verbose_name_plural': '收藏表',
                'db_table': 'a_collection',
            },
        ),
    ]
