# Generated by Django 3.2.16 on 2023-03-04 22:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import extension.custom_field_ext


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0002_album_author'),
        ('user', '0005_alter_user_username'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='创建时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='创建时间戳')),
                ('update_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='更新时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='更新时间戳')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='照片名')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='照片地址')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('status', models.CharField(choices=[('0', '公开'), ('1', '私密')], default='0', max_length=1, verbose_name='状态')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.album', verbose_name='相册')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='作者')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tag.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '照片表',
                'verbose_name_plural': '照片表',
                'db_table': 'photo',
            },
        ),
    ]
