# Generated by Django 3.2.16 on 2023-03-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photo_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='a_photo',
        ),
    ]
