# Generated by Django 3.2.16 on 2023-05-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partition', '0001_initial'),
        ('photo', '0002_photo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='partition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partition.partition', verbose_name='分区'),
        ),
    ]
