# Generated by Django 3.2.16 on 2023-04-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20230420_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-create_time'], 'verbose_name': '照片表', 'verbose_name_plural': '照片表'},
        ),
    ]
