# Generated by Django 3.2.16 on 2023-04-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20230425_1631'),
        ('tag', '0002_alter_tag_table'),
        ('photo', '0005_alter_photo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.album', verbose_name='相册'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tag.tag', verbose_name='标签'),
        ),
    ]
