# Generated by Django 3.2.16 on 2023-04-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20230425_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='click',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
    ]
