# Generated by Django 3.2.16 on 2023-05-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_photo_click'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tag',
        ),
    ]
