# Generated by Django 3.2.16 on 2023-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jwt_version',
            field=models.IntegerField(default=0, verbose_name='jwt版本'),
        ),
    ]
