# Generated by Django 3.2.16 on 2023-03-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='a_user',
        ),
    ]
