# Generated by Django 3.2.16 on 2023-05-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='封面'),
        ),
    ]
