# Generated by Django 3.2.16 on 2023-02-25 17:46

import django.core.validators
from django.db import migrations, models
import extension.custom_field_ext


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='创建时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='创建时间戳')),
                ('update_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='更新时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='更新时间戳')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='相册名')),
                ('cover', models.CharField(blank=True, default='', max_length=255, verbose_name='封面')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '相册表',
                'verbose_name_plural': '相册表',
                'db_table': 'album',
            },
        ),
    ]
