# Generated by Django 3.2.16 on 2023-05-03 17:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import extension.custom_field_ext


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='创建时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='创建时间戳')),
                ('update_time', extension.custom_field_ext.TimestampField(blank=True, editable=False, help_text='更新时间戳', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='更新时间戳')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='相册名')),
                ('cover', models.CharField(blank=True, max_length=255, null=True, verbose_name='封面')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='作者')),
            ],
            options={
                'verbose_name': '相册表',
                'verbose_name_plural': '相册表',
                'db_table': 'a_album',
            },
        ),
    ]
