# Generated by Django 3.2.16 on 2023-03-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='a_album',
        ),
    ]
