# Generated by Django 3.2.16 on 2023-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.CharField(max_length=255, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='album',
            name='desc',
            field=models.CharField(max_length=255, null=True, verbose_name='描述'),
        ),
    ]
