# Generated by Django 3.2.16 on 2023-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20230421_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='album',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
    ]
