# Generated by Django 3.2.16 on 2023-05-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collect',
        ),
    ]
